### ISSUE TITLE
Duplicate json values cause unexpected EOF

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/dgo#18] opened 2020-03-05 08:32 UTC
Discovered with the hiera_terraform plugin, the following state file causes UnmarshalJSON to panic

```json
{
  "version": 3,
  "serial": 1,
  "modules": [
    {
      "path": [
        "root"
      ],
      "outputs": {
        "test": {
          "sensitive": false,
          "type": "string",
          "value": "value"
        },
        "testobject": {
          "value": {
            "key1": "value1",
            "key2": "value2"
          }
        },
        "test1": {
          "value": {
            "array_property": [
              {
                "thing1": "xxxxxxxxxxxxxxxxxxxxx",
                "thing2": "xxxxxxxxxxxxxxxxxxxxx"
              }
            ]
          }
        }
      },
      "resources": {},
      "depends_on": []
    }
  ]
}
```

After adding the `test` property and running the `terraform_backend_test.go` 

```
Running tool: C:\Go\bin\go.exe test -timeout 30s github.com/lyraproj/hiera_terraform -run ^(TestLookup_TerraformBackend)$

--- FAIL: TestLookup_TerraformBackend (0.00s)
panic: unexpected EOF [recovered]
	panic: unexpected EOF

goroutine 11 [running]:
testing.tRunner.func1.1(0x16b5b80, 0xc000088040)
	c:/go/src/testing/testing.go:941 +0x3d7
testing.tRunner.func1(0xc0000f0900)
	c:/go/src/testing/testing.go:944 +0x400
panic(0x16b5b80, 0xc000088040)
	c:/go/src/runtime/panic.go:967 +0x16b
github.com/lyraproj/dgo/streamer.(*jsonDecoder).nextToken(0xc000723a00, 0x20, 0xc000023310)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:132 +0x111
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeElem(0xc000723a00, 0xc00000005d, 0x1511d45)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:68 +0x36
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeArray(0xc000723a00)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:112 +0x3a
github.com/lyraproj/dgo/streamer.(*BasicCollector).AddArray(0xc000704780, 0x0, 0xc000701ad0)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/basiccollector.go:39 +0x133
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeCollection(0xc000723a00, 0x7d)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:107 +0x2ce
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeElem(0xc000723a00, 0xc00000005d, 0x1511d01)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:73 +0x30b
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeArray(0xc000723a00)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:112 +0x3a
github.com/lyraproj/dgo/streamer.(*BasicCollector).AddArray(0xc000704780, 0x0, 0xc0007019a0)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/basiccollector.go:39 +0x133
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeCollection(0xc000723a00, 0x7d)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:107 +0x2ce
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeElem(0xc000723a00, 0xc00000005d, 0x1511d01)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:73 +0x30b
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeArray(0xc000723a00)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:112 +0x3a
github.com/lyraproj/dgo/streamer.(*BasicCollector).AddArray(0xc000704780, 0x0, 0xc0007018a0)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/basiccollector.go:39 +0x133
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeCollection(0xc000723a00, 0x5b)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:107 +0x2ce
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeElem(0xc000723a00, 0x7d, 0x1)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:73 +0x30b
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeMap(0xc000723a00)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:117 +0x3a
github.com/lyraproj/dgo/streamer.(*BasicCollector).AddMap(0xc000704780, 0x0, 0xc000701880)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/basiccollector.go:51 +0x154
github.com/lyraproj/dgo/streamer.(*dataDecoder).AddMap(0xc000704780, 0x0, 0xc000701880)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/decoder.go:35 +0x4c
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeCollection(0xc000723a00, 0x7b)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:96 +0xd8
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeElem(0xc000723a00, 0x7d, 0x1)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:73 +0x30b
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeMap(0xc000723a00)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:117 +0x3a
github.com/lyraproj/dgo/streamer.(*BasicCollector).AddMap(0xc000704780, 0x0, 0xc000701820)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/basiccollector.go:51 +0x154
github.com/lyraproj/dgo/streamer.(*dataDecoder).AddMap(0xc000704780, 0x0, 0xc000701820)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/decoder.go:35 +0x4c
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeCollection(0xc000723a00, 0x7b)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:96 +0xd8
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decodeElem(0xc000723a00, 0x0, 0xc000704780)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:73 +0x30b
github.com/lyraproj/dgo/streamer.(*jsonDecoder).decode(...)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:64
github.com/lyraproj/dgo/streamer.UnmarshalJSON(0xc0000c6000, 0x94, 0x116, 0x0, 0x0, 0xd, 0x0)
	C:/Source/go/pkg/mod/github.com/lyraproj/dgo@v0.4.2/streamer/json.go:50 +0x238
github.com/lyraproj/hiera_terraform.testTerraformPlugin(0xc0000f0900, 0xc00006dd70, 0xc8, 0x1923780, 0xc000722ec0)
	c:/Source/go/hiera_terraform/terraform_backend_test.go:90 +0x528
github.com/lyraproj/hiera_terraform.TestLookup_TerraformBackend(0xc0000f0900)
	c:/Source/go/hiera_terraform/terraform_backend_test.go:21 +0x2a1
testing.tRunner(0xc0000f0900, 0x19d4a68)
	c:/go/src/testing/testing.go:992 +0xe3
created by testing.(*T).Run
	c:/go/src/testing/testing.go:1043 +0x35e
FAIL	github.com/lyraproj/hiera_terraform	0.721s
FAIL
Error: Tests failed.
```

If `thing1` and `thing2` have different values it works

**Comment by thallgren** [comment] 2020-03-05 15:32
Sorry about that. This was caused by an oversight in the implementation of the dgo JSON decoder (forgot to consume the ending curly brace of a `{ "__ref": <n> }` and an insufficient unit test. Fixed in dgo/hiera v0.4.3.

**Closed by thallgren** 2020-03-05 15:32 UTC
